### PR TITLE
Add `exclude.yml` file

### PR DESCRIPTION
**Pull request by valosekj**
During the control of QC for vertebral labeling, we encountered the subject `sub-cal088_ses-M0` who is already included in the [issue regarding the T2w poor data quality](https://github.com/ivadomed/canproco/issues/6). But so far, we do not have any way how to exclude problematic subjects from the analysis. 
Thus, this PR adds the `exclude.yml` file that lists all subjects who should be excluded from the analysis. These subjects will be also listed within the [`data-quality` issues](https://github.com/ivadomed/canproco/issues/6).

Now, there is a question about how to use this `exclude.yml` file. Basically, we have a few ideas with @mchen1110:
1. Load the `exclude.yml` file in the [sct-preprocess_data.sh](https://github.com/ivadomed/canproco/blob/main/preprocess/sct-preprocess_data.sh), add a condition, and exclude the subject from the preprocessing.
2. Exclude the subjects directly within the `sct_run_batch` script using `-exclude-list` flag. This is probably a bit more complicated since there is probably no way how to load the `exclude.yml` to the `sct_run_batch` script. Instead, we would have to specify subjects in the `-exclude-list` list; for example by copy/paste from `exclude.yml`, which is however error-prone.
3. Run the bash preprocessing for all subjects and exclude subjects during future statistical analysis. (this approach was used in the [spine-generic](https://github.com/spine-generic/spine-generic/blob/3aa69465063d823088b2c819d3ad9b81725b2fc8/spinegeneric/cli/generate_figure.py#L237-L238) and [ukbiobank-spinalcord-csa](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/blob/04b9dd20bf2ad646e734e3e3effae174d4e451ca/README.md#compute-statistical-analysis))

Summary: When to exclude the subjects? During the preprocessing or after that during the final analysis?

### CODE REVIEW

**Comment by sandrinebedard** [comment]
I would go with option 1:

> Load the exclude.yml file in the [sct-preprocess_data.sh](https://github.com/ivadomed/canproco/blob/main/preprocess/sct-preprocess_data.sh), add a condition, and exclude the subject from the preprocessing.

Since we want to train models for lesion segmentation, we won't have a proper ground truth for that image, so we don't want to copy it in our `data_processed_clean`, so I think it would be better to not run the analysis on these images. 

In uk-biobank and spine generic, the purpose wasn't training, it was statistical analysis, so it was easy to exlcude it afterwards!

You can pass the list using: `-script-args exclude.yml`
As done in contrast-agnostic: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/1a43ed4a0ea72f9d872aa80838cb0bde6a8db3d5/process_data.sh#L266-L286

It would be a bit different in our case, but the same concept.

**Comment by jcohenadad** [comment]
> This is probably a bit more complicated since there is probably no way how to load the exclude.yml to the sct_run_batch script.

let's make a modification to SCT then 😊  could you please open a feature request?

apart from this useful feature, I agree with @sandrinebedard 's suggestion in https://github.com/ivadomed/canproco/pull/10#issuecomment-1335523058

**Comment by valosekj** [comment]
> > This is probably a bit more complicated since there is probably no way how to load the exclude.yml to the sct_run_batch script.
> 
> let's make a modification to SCT then 😊 could you please open a feature request?

Sure, the feature request [opened](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971).

Before the merge of this PR, I am now just thinking about the format of the exclude file.

Currently, [I use](https://github.com/ivadomed/canproco/blob/b5177c2da3a5fb304cc51975bc43dc67a367153c/etc/exclude.yml) the following key-value structure:

```
t2w:
   - sub-cal088_ses-M0   # Poor data quality
   - sub-cal209_ses-M0   # Missing T2w file
```

Alternatively, filenames structure could be used (as done in [ukbiobank-spinalcord-csa](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/blob/04b9dd20bf2ad646e734e3e3effae174d4e451ca/exclude.yml)):

```
...
- sub-1002702_T1w.nii.gz  # Motion artifact
- sub-1005491_T2w.nii.gz  # Don't see C2-3 disc, image tilted
...
```

Personally, I like the key-value structure since it groups images for individual contrasts (easier to read). 
But maybe, at the end, it doesn't matter because the exclusion will be done based on the subjectID which can be fetched from both.

**Comment by joshuacwnewton** [comment]
I proposed an idea in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971#issuecomment-1336218987 for how SCT could potentially parse `exclude.yml` files.

> I am now just thinking about the format of the exclude file [...]

Of the two yaml formats (key/value vs. list), I think the plain list formatting would be easier to work with on SCT's end?

Since, parsing the following:

> ```yaml
> t2w:
>    - sub-cal088_ses-M0   # Poor data quality
>    - sub-cal209_ses-M0   # Missing T2w file
> ```

Would lead to:

```python
{exclude_list: {t2w: ['sub-cal088_ses-M0', 'sub-cal209_ses-M0']}}
```

Which would require SCT to remove the inner `t2w` dictionary (and other dictionaries, if more contrasts are present).

**Comment by joshuacwnewton** [comment]
> Personally, I like the key-value structure since it groups images for individual contrasts (easier to read). 

@valosekj if you want to still group subjects for readability purposes, but keep a single-line structure, I think you could do something like:

```yaml
# t2w subjects
- sub-cal088_ses-M0   # Poor data quality
- sub-cal209_ses-M0   # Missing T2w file
# t1w subjects
- sub-cal088_ses-M0   # Poor data quality
- sub-cal209_ses-M0   # Missing T1w file
```

Since YAML supports single-line comments.

**Comment by valosekj** [comment]
@joshuacwnewton Thank you for [the proposed solution](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971#issuecomment-1336218987)!

> @valosekj if you want to still group subjects for readability purposes, but keep a flat-list structure, I _think_ you could do something like:
> 
> ```yaml
> # t2w files
> - sub-cal088_ses-M0   # Poor data quality
> - sub-cal209_ses-M0   # Missing T2w file
> # t1w files
> - sub-cal088_ses-M0   # Poor data quality
> - sub-cal209_ses-M0   # Missing T1w file
> ```

The single-line comment YAML formatting is also elegant! I updated the YAML file in https://github.com/ivadomed/canproco/pull/10/commits/ba75f366b65d49449e8a2a978b51b070523ee581

**Comment by joshuacwnewton** [comment]
> It may be better to continue with that format since it is the one from the QC, where we identify problematic images!

The tricky thing with that is, as @jcohenadad previously pointed out , the `-exclude_list` argument in SCT [can only filter directories](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971#issuecomment-1336249269), and not individual files. 

> _Aside: The fact that the QC `.yml` output isn't compatible with `-exclude_list` is perhaps worth investigating, though? But, maybe a bit out of scope for this discussion, hm._ :thinking:

**Comment by valosekj** [comment]
> You could also direclty get the contrast if you keep the entire image name. Such as it is when you download the qc_artifact in the QC report. It may be better to continue with that format since it is the one from the QC, where we identify problematic images!
> 
> For now, we have the entire image path:
> 
> ```
> FILES_LABEL:
>     - /mnt/extrassd1/janvalosek/canproco_labeling_T2w_2022-11-30/data_processed/sub-mon207/ses-M0/anat/sub-mon207_ses-M0_T2w.nii.gz
> ```

Yes, you are right. But this works only in subjects where QC is generated (i.e., function successfully finished). But for some subjects, the image can be completely missing (like for `sub-cal209_ses-M0`), or the function fails, and QC is not generated.


> But we have the `FILES_LABEL` we don't necessarly want

Yeah, and we can also have other labels like `FILES_SEG`...

Also, Joshua pointed out that `.nii.gz` suffix is currently [not supported](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971#issuecomment-1336249269).

**Comment by joshuacwnewton** [comment]
I have some additional thoughts, but, for now, perhaps we could keep this PR as-is (since it's a manually-curated list that is specific to this project, separate from SCT's QC feature).

Then, follow-up in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971 (or a separate issue) to discuss ideas for updating the QC yml outputs so that they are compatible with SCT's `-exclude-list` feature.

**Comment by valosekj** [comment]
> I have some additional thoughts, but, for now, perhaps we could keep this PR as-is (since it's a manually-curated list that is specific to this project, separate from SCT's QC feature).
> 
> Then, follow-up in [spinalcordtoolbox/spinalcordtoolbox#3971](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971) (or a separate issue) to discuss ideas for updating the QC yml outputs so that they are compatible with SCT's `-exclude-list` feature.

I agree. I merged the PR. We can continue with the discussion in the SCT [spinalcordtoolbox/spinalcordtoolbox#3971](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3971) issue.

**Pull request merged**
